# Generated by Django 3.2.6 on 2024-10-08 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generarreportes', '0002_auto_20241007_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='descuento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generarreportes.descuento'),
        ),
    ]
